import type { Company, EmployerQuestion, Internship } from "@/lib/types";

const RIGHT_TO_WORK_OPTIONS = [
  "I'm an Australian citizen",
  "I'm a permanent resident and/or NZ citizen",
  "I have a family/partner visa with no work restrictions",
  "I have a graduate temporary work visa",
  "I have a student visa with work rights",
  "I have a holiday working visa",
  "I require sponsorship to work for a new employer",
];

const STUDY_OPTIONS = [
  "Not yet enrolled",
  "Currently studying (1st year)",
  "Currently studying (2nd year)",
  "Currently studying (penultimate year)",
  "Currently studying (final year)",
  "Recently graduated",
];

function baseQuestions(extra: EmployerQuestion[] = []): EmployerQuestion[] {
  return [
    {
      id: "right-to-work",
      label: "Which of the following statements best describes your right to work in Australia?",
      type: "select",
      options: RIGHT_TO_WORK_OPTIONS,
      required: true,
    },
    {
      id: "study-status",
      label: "What is your current study status?",
      type: "select",
      options: STUDY_OPTIONS,
      required: true,
    },
    ...extra,
  ];
}

export const companies: Company[] = [
  {
    id: "canopy-labs",
    name: "Canopy Labs",
    industry: "Design & Product Studio",
    size: "51-200 employees",
    about:
      "Canopy Labs is a Brisbane product studio building digital experiences for health, education and climate startups. We pair junior talent with senior mentors on real client work from day one.",
    verified: true,
    color: "#246bfe",
    tagline: "Designing products people trust",
  },
  {
    id: "northstar-systems",
    name: "Northstar Systems",
    industry: "Information Technology",
    size: "201-500 employees",
    about:
      "Northstar Systems is an Australian cloud engineering company helping enterprises modernise their platforms. Our internship pathway is a structured 8-week program with weekly mentoring.",
    verified: true,
    color: "#22c7a9",
    tagline: "Cloud platforms, built to last",
  },
  {
    id: "sunday-studio",
    name: "Sunday Studio",
    industry: "Marketing & Creative",
    size: "11-50 employees",
    about:
      "Sunday Studio is a brand and content studio in Melbourne working with hospitality, fashion and lifestyle clients. We are a small, fast team that gives interns real ownership.",
    verified: true,
    color: "#ff6b4a",
    tagline: "Brands worth talking about",
  },
  {
    id: "clearcurrent",
    name: "ClearCurrent",
    industry: "Renewable Energy",
    size: "51-200 employees",
    about:
      "ClearCurrent is a renewable-energy analytics company in Perth helping networks plan for a cleaner grid. We hire curious students who care about the energy transition.",
    verified: true,
    color: "#8b5cf6",
    tagline: "Powering the energy transition",
  },
  {
    id: "meridian-health",
    name: "Meridian Health",
    industry: "Healthcare & Medical",
    size: "500-1,000 employees",
    about:
      "Meridian Health runs allied-health and community clinics across Queensland. Our placements give students supervised, hands-on exposure to real clinical operations.",
    verified: true,
    color: "#0ea5e9",
    tagline: "Care, closer to community",
  },
  {
    id: "ledgerline",
    name: "Ledgerline",
    industry: "Accounting & Finance",
    size: "51-200 employees",
    about:
      "Ledgerline is a modern accounting and advisory firm working with Australian small businesses. Interns rotate across bookkeeping, tax and advisory teams.",
    verified: true,
    color: "#16a34a",
    tagline: "Numbers that move businesses forward",
  },
  {
    id: "harbour-legal",
    name: "Harbour Legal",
    industry: "Legal Services",
    size: "11-50 employees",
    about:
      "Harbour Legal is a boutique commercial law firm in Sydney. Our clerkship gives students structured exposure to contracts, research and client matters.",
    verified: false,
    color: "#1e3a8a",
    tagline: "Practical, commercial legal advice",
  },
  {
    id: "atlas-engineering",
    name: "Atlas Engineering",
    industry: "Engineering & Construction",
    size: "201-500 employees",
    about:
      "Atlas Engineering delivers civil and structural projects across Australia. Our vacation program puts students alongside project engineers on live infrastructure.",
    verified: true,
    color: "#f59e0b",
    tagline: "Building the infrastructure that connects us",
  },
  {
    id: "brightpath-education",
    name: "Brightpath Education",
    industry: "Education & Training",
    size: "51-200 employees",
    about:
      "Brightpath Education builds learning programs for schools and community groups. Interns help design lessons, run workshops and measure outcomes.",
    verified: false,
    color: "#db2777",
    tagline: "Learning that changes outcomes",
  },
  {
    id: "tidewell-research",
    name: "Tidewell Research",
    industry: "Science & Research",
    size: "11-50 employees",
    about:
      "Tidewell Research is a marine and environmental science group in Hobart. We give students field and lab experience on funded research projects.",
    verified: true,
    color: "#0d9488",
    tagline: "Science for healthier oceans",
  },
];

export const internships: Internship[] = [
  {
    id: "product-design-intern",
    role: "Product Design Intern",
    companyId: "canopy-labs",
    company: "Canopy Labs",
    location: "Brisbane, QLD",
    mode: "Hybrid",
    workType: "Part-time",
    field: "Design",
    classification: "Design & Architecture (UX & Interaction Design)",
    salary: "$32 – $38 per hour",
    duration: "12 weeks",
    postedDaysAgo: 2,
    applicantVolume: "High",
    paid: true,
    friendly: true,
    credit: true,
    color: "#246bfe",
    summary: "Work on real client product design with senior mentors across a 12-week paid placement.",
    about:
      "Canopy Labs is an award-winning product studio based in Brisbane, working with health, education and climate startups to design digital products people trust.",
    responsibilities:
      "You will join a product squad and contribute to live client work — running research, sketching flows, building Figma prototypes and helping ship features. You will receive weekly mentoring from a senior designer and finish with a portfolio-ready case study.",
    perks: [
      "Paid hourly rate + portfolio case study",
      "Weekly 1:1 mentoring with a senior designer",
      "Hybrid working — 2 days in our Brisbane studio",
      "Academic credit available",
      "Real client work from week one",
    ],
    requirements: [
      "Currently studying design, HCI or a related field",
      "A portfolio or coursework showing your design thinking",
      "Comfortable with Figma (or keen to learn fast)",
      "Available 3 days per week for 12 weeks",
    ],
    questions: baseQuestions([
      {
        id: "portfolio",
        label: "Please share a link to your portfolio or design work.",
        type: "text",
        required: true,
      },
    ]),
  },
  {
    id: "software-engineering-intern",
    role: "Software Engineering Intern",
    companyId: "northstar-systems",
    company: "Northstar Systems",
    location: "Sydney, NSW",
    mode: "Remote",
    workType: "Full-time",
    field: "Technology",
    classification: "Information & Communication Technology (Developers/Programmers)",
    salary: "$1,400 – $1,700 per week",
    duration: "8 weeks",
    postedDaysAgo: 1,
    applicantVolume: "High",
    paid: true,
    friendly: true,
    credit: false,
    color: "#22c7a9",
    summary: "A structured 8-week remote engineering program with weekly mentoring and a capstone project.",
    about:
      "Northstar Systems is an Australian cloud engineering company helping enterprises modernise their platforms. Our internship is a structured program with real production exposure.",
    responsibilities:
      "You will pair with engineers on a squad, pick up tickets from our backlog, write tests and ship code to staging. You will work in TypeScript and Node, learn our CI/CD pipeline and present a capstone at the end.",
    perks: [
      "Fully remote across Australia",
      "Competitive weekly pay",
      "Paid learning time and certifications",
      "Mentor-led code reviews",
      "Capstone you can show employers",
    ],
    requirements: [
      "Studying computer science, software engineering or similar",
      "Some experience with a modern language (JS/TS, Python, Java...)",
      "Git basics and a willingness to learn our stack",
      "Available full-time for 8 weeks",
    ],
    questions: baseQuestions([
      {
        id: "languages",
        label: "Which programming languages are you most comfortable with?",
        type: "text",
        required: true,
      },
    ]),
  },
  {
    id: "brand-marketing-intern",
    role: "Brand Marketing Intern",
    companyId: "sunday-studio",
    company: "Sunday Studio",
    location: "Melbourne, VIC",
    mode: "On-site",
    workType: "Casual",
    field: "Marketing",
    classification: "Marketing & Communications (Brand Management)",
    salary: "$30 – $34 per hour",
    duration: "12 weeks",
    postedDaysAgo: 4,
    applicantVolume: "Typical",
    paid: true,
    friendly: false,
    credit: true,
    color: "#ff6b4a",
    summary: "Help run brand and content campaigns for hospitality and lifestyle clients in a small fast studio.",
    about:
      "Sunday Studio is a brand and content studio working with hospitality, fashion and lifestyle clients. We are a small team that gives interns real ownership early.",
    responsibilities:
      "You will support campaign planning, draft social content, help on shoots and report on performance. You will sit with strategists and designers and own a small client project by the end.",
    perks: [
      "Hands-on work with real brands",
      "On-set experience at content shoots",
      "Academic credit available",
      "A reference and case study at the end",
    ],
    requirements: [
      "Studying marketing, communications or media",
      "Strong writing and a good eye for content",
      "Organised and comfortable juggling tasks",
      "Available 2-3 days per week in Melbourne",
    ],
    questions: baseQuestions(),
  },
  {
    id: "sustainability-analyst-intern",
    role: "Sustainability Analyst Intern",
    companyId: "clearcurrent",
    company: "ClearCurrent",
    location: "Perth, WA",
    mode: "Hybrid",
    workType: "Part-time",
    field: "Science",
    classification: "Science & Technology (Environmental)",
    salary: "$31 – $36 per hour",
    duration: "6 weeks",
    postedDaysAgo: 6,
    applicantVolume: "Typical",
    paid: false,
    friendly: true,
    credit: true,
    color: "#8b5cf6",
    summary: "Support renewable-energy analytics and reporting on a credit-eligible placement.",
    about:
      "ClearCurrent is a renewable-energy analytics company helping networks plan for a cleaner grid. We hire curious students who care about the energy transition.",
    responsibilities:
      "You will help collect and clean energy datasets, build simple models and contribute to client sustainability reports. You will learn how analytics informs real grid decisions.",
    perks: [
      "Meaningful work on the energy transition",
      "Academic credit placement",
      "Hybrid — 2 days in our Perth office",
      "Mentoring from senior analysts",
    ],
    requirements: [
      "Studying environmental science, engineering or data",
      "Comfortable with spreadsheets; bonus for Python/R",
      "Curiosity about energy and sustainability",
      "Available 2 days per week for 6 weeks",
    ],
    questions: baseQuestions(),
  },
  {
    id: "cyber-security-intern",
    role: "Cyber Security Intern",
    companyId: "northstar-systems",
    company: "Northstar Systems",
    location: "Remote",
    mode: "Remote",
    workType: "Part-time",
    field: "Technology",
    classification: "Information & Communication Technology (Security)",
    salary: "$34 – $40 per hour",
    duration: "10 weeks",
    postedDaysAgo: 3,
    applicantVolume: "High",
    paid: true,
    friendly: true,
    credit: false,
    color: "#22c7a9",
    summary: "Hands-on exposure to security operations, monitoring and reporting on a remote placement.",
    about:
      "Northstar Systems runs a small security team protecting enterprise cloud platforms. This placement is designed for students building toward a security career.",
    responsibilities:
      "You will shadow our security operations team, help triage alerts, document findings and assist with vulnerability reporting. You will learn the tools and process behind a real SOC.",
    perks: [
      "Fully remote",
      "Mentoring from security engineers",
      "Exposure to real SOC tooling",
      "Pathway to a graduate role",
    ],
    requirements: [
      "Studying cyber security, IT or computer science",
      "Understanding of networking and security basics",
      "Careful, detail-oriented and discreet",
      "Available 2-3 days per week for 10 weeks",
    ],
    questions: baseQuestions([
      {
        id: "security-interest",
        label: "What area of security interests you most, and why?",
        type: "text",
        required: false,
      },
    ]),
  },
  {
    id: "data-analyst-intern",
    role: "Data Analyst Intern",
    companyId: "ledgerline",
    company: "Ledgerline",
    location: "Brisbane, QLD",
    mode: "Hybrid",
    workType: "Part-time",
    field: "Technology",
    classification: "Information & Communication Technology (Business/Systems Analysts)",
    salary: "$30 – $35 per hour",
    duration: "12 weeks",
    postedDaysAgo: 5,
    applicantVolume: "Typical",
    paid: true,
    friendly: true,
    credit: true,
    color: "#16a34a",
    summary: "Turn messy business data into clear dashboards and insights for small-business clients.",
    about:
      "Ledgerline is a modern accounting and advisory firm. Our data team helps clients understand their numbers through clean reporting.",
    responsibilities:
      "You will help build dashboards, tidy datasets and prepare insights for client reviews. You will learn how data supports real business decisions.",
    perks: [
      "Real client reporting work",
      "Academic credit available",
      "Hybrid working in Brisbane",
      "Mentoring from senior analysts",
    ],
    requirements: [
      "Studying data, IT, commerce or stats",
      "Comfortable with Excel; bonus for SQL/Power BI",
      "Clear communicator",
      "Available 2-3 days per week for 12 weeks",
    ],
    questions: baseQuestions(),
  },
  {
    id: "physiotherapy-assistant-intern",
    role: "Physiotherapy Assistant Intern",
    companyId: "meridian-health",
    company: "Meridian Health",
    location: "Gold Coast, QLD",
    mode: "On-site",
    workType: "Casual",
    field: "Health",
    classification: "Healthcare & Medical (Physiotherapy, OT & Rehabilitation)",
    salary: "$29 – $33 per hour",
    duration: "8 weeks",
    postedDaysAgo: 7,
    applicantVolume: "Typical",
    paid: true,
    friendly: true,
    credit: true,
    color: "#0ea5e9",
    summary: "Supervised, hands-on experience supporting physiotherapists in a busy community clinic.",
    about:
      "Meridian Health runs allied-health and community clinics across Queensland. Our placements give students supervised exposure to real clinical operations.",
    responsibilities:
      "You will support physiotherapists with patient setup, exercise supervision and clinic operations under guidance. You will gain genuine clinical exposure in a supportive team.",
    perks: [
      "Supervised clinical experience",
      "Academic credit placement",
      "Supportive allied-health team",
      "Pathway references for graduates",
    ],
    requirements: [
      "Studying physiotherapy, exercise science or allied health",
      "Current student with relevant coursework",
      "Warm, patient and professional manner",
      "Available 2 days per week for 8 weeks",
    ],
    questions: baseQuestions(),
  },
  {
    id: "accounting-intern",
    role: "Accounting Intern",
    companyId: "ledgerline",
    company: "Ledgerline",
    location: "Brisbane, QLD",
    mode: "On-site",
    workType: "Part-time",
    field: "Business",
    classification: "Accounting (Bookkeeping & Small Practice Accounting)",
    salary: "$28 – $32 per hour",
    duration: "12 weeks",
    postedDaysAgo: 9,
    applicantVolume: "Typical",
    paid: true,
    friendly: true,
    credit: true,
    color: "#16a34a",
    summary: "Rotate across bookkeeping, tax and advisory teams at a modern accounting firm.",
    about:
      "Ledgerline works with Australian small businesses across bookkeeping, tax and advisory. Interns rotate across teams to build a broad foundation.",
    responsibilities:
      "You will assist with bookkeeping, prepare working papers, support tax returns and observe client advisory meetings. You will see how a modern practice operates end to end.",
    perks: [
      "Rotations across multiple teams",
      "Academic credit available",
      "Mentoring toward CA/CPA pathways",
      "Genuine graduate pipeline",
    ],
    requirements: [
      "Studying accounting or commerce",
      "Solid attention to detail",
      "Comfortable with Excel",
      "Available 2-3 days per week for 12 weeks",
    ],
    questions: baseQuestions(),
  },
  {
    id: "legal-clerk-intern",
    role: "Legal Clerk Intern",
    companyId: "harbour-legal",
    company: "Harbour Legal",
    location: "Sydney, NSW",
    mode: "On-site",
    workType: "Part-time",
    field: "Law",
    classification: "Legal (Law Clerks & Paralegals)",
    salary: "$30 – $36 per hour",
    duration: "10 weeks",
    postedDaysAgo: 11,
    applicantVolume: "Low",
    paid: true,
    friendly: false,
    credit: true,
    color: "#1e3a8a",
    summary: "Structured clerkship with exposure to contracts, legal research and client matters.",
    about:
      "Harbour Legal is a boutique commercial law firm in Sydney. Our clerkship gives students structured exposure across commercial matters.",
    responsibilities:
      "You will help with legal research, draft simple documents, prepare briefs and observe client meetings under supervision. You will build practical commercial-law skills.",
    perks: [
      "Real commercial-law exposure",
      "Academic credit available",
      "Mentoring from practising lawyers",
      "Strong reference for future clerkships",
    ],
    requirements: [
      "Studying law (penultimate or final year preferred)",
      "Strong research and writing",
      "Professional and discreet",
      "Available 2 days per week for 10 weeks",
    ],
    questions: baseQuestions(),
  },
  {
    id: "civil-engineering-vacation",
    role: "Civil Engineering Vacation Student",
    companyId: "atlas-engineering",
    company: "Atlas Engineering",
    location: "Perth, WA",
    mode: "On-site",
    workType: "Vacation",
    field: "Engineering",
    classification: "Engineering (Civil/Structural Engineering)",
    salary: "$1,200 – $1,500 per week",
    duration: "10 weeks",
    postedDaysAgo: 8,
    applicantVolume: "High",
    paid: true,
    friendly: false,
    credit: false,
    color: "#f59e0b",
    summary: "A paid summer vacation program alongside project engineers on live infrastructure.",
    about:
      "Atlas Engineering delivers civil and structural projects across Australia. Our vacation program puts students on real infrastructure projects.",
    responsibilities:
      "You will support project engineers with design checks, site visits, documentation and reporting. You will experience how major infrastructure is delivered.",
    perks: [
      "Competitive weekly pay",
      "Site visits to live projects",
      "Mentoring from project engineers",
      "Graduate program pathway",
    ],
    requirements: [
      "Studying civil or structural engineering",
      "Penultimate-year student preferred",
      "Comfortable with engineering software",
      "Available full-time over summer",
    ],
    questions: baseQuestions(),
  },
  {
    id: "ux-research-intern",
    role: "UX Research Intern",
    companyId: "canopy-labs",
    company: "Canopy Labs",
    location: "Remote",
    mode: "Remote",
    workType: "Part-time",
    field: "Design",
    classification: "Design & Architecture (User Experience & Research)",
    salary: "$31 – $36 per hour",
    duration: "8 weeks",
    postedDaysAgo: 3,
    applicantVolume: "Typical",
    paid: true,
    friendly: true,
    credit: true,
    color: "#246bfe",
    summary: "Run interviews and usability tests that shape real product decisions, fully remote.",
    about:
      "Canopy Labs pairs junior talent with senior mentors on real client work. Our research team turns user insight into product direction.",
    responsibilities:
      "You will help plan and run interviews, synthesise findings and present insights to product squads. You will learn a complete research workflow end to end.",
    perks: [
      "Fully remote",
      "Mentoring from senior researchers",
      "Academic credit available",
      "Portfolio-ready research case study",
    ],
    requirements: [
      "Studying HCI, psychology, design or related",
      "Good communicator and curious listener",
      "Organised note-taker",
      "Available 2-3 days per week for 8 weeks",
    ],
    questions: baseQuestions(),
  },
  {
    id: "digital-marketing-intern",
    role: "Digital Marketing Intern",
    companyId: "sunday-studio",
    company: "Sunday Studio",
    location: "Remote",
    mode: "Remote",
    workType: "Casual",
    field: "Marketing",
    classification: "Marketing & Communications (Digital & Search Marketing)",
    salary: "$28 – $32 per hour",
    duration: "12 weeks",
    postedDaysAgo: 1,
    applicantVolume: "High",
    paid: true,
    friendly: true,
    credit: false,
    color: "#ff6b4a",
    summary: "Support SEO, email and paid-social campaigns and learn analytics hands-on.",
    about:
      "Sunday Studio helps brands grow online. Our digital team runs search, social and email campaigns for lifestyle clients.",
    responsibilities:
      "You will help schedule content, support paid-social and email campaigns and report on results in analytics. You will learn the levers behind digital growth.",
    perks: [
      "Fully remote and flexible",
      "Hands-on with real ad budgets",
      "Mentoring from growth marketers",
      "First-internship friendly",
    ],
    requirements: [
      "Studying marketing, business or media",
      "Curious about analytics and content",
      "Reliable and organised",
      "Available 2 days per week for 12 weeks",
    ],
    questions: baseQuestions(),
  },
  {
    id: "primary-teaching-aide-intern",
    role: "Education Program Intern",
    companyId: "brightpath-education",
    company: "Brightpath Education",
    location: "Adelaide, SA",
    mode: "Hybrid",
    workType: "Part-time",
    field: "Education",
    classification: "Education & Training (Teaching Aides & Special Needs)",
    salary: "$28 – $31 per hour",
    duration: "10 weeks",
    postedDaysAgo: 12,
    applicantVolume: "Low",
    paid: true,
    friendly: true,
    credit: true,
    color: "#db2777",
    summary: "Help design lessons and run workshops with a team that builds learning programs.",
    about:
      "Brightpath Education builds learning programs for schools and community groups. Interns help create and deliver real lessons.",
    responsibilities:
      "You will help design lesson materials, support workshop delivery and measure learning outcomes. You will see how good programs are built and improved.",
    perks: [
      "Meaningful, people-facing work",
      "Academic credit placement",
      "Mentoring from program designers",
      "First-internship friendly",
    ],
    requirements: [
      "Studying education, psychology or community work",
      "Warm and confident with groups",
      "Organised and reliable",
      "Available 2 days per week for 10 weeks",
    ],
    questions: baseQuestions(),
  },
  {
    id: "marine-research-intern",
    role: "Marine Research Intern",
    companyId: "tidewell-research",
    company: "Tidewell Research",
    location: "Hobart, TAS",
    mode: "On-site",
    workType: "Vacation",
    field: "Science",
    classification: "Science & Technology (Biological & Biomedical Sciences)",
    salary: "$30 – $34 per hour",
    duration: "8 weeks",
    postedDaysAgo: 14,
    applicantVolume: "Typical",
    paid: true,
    friendly: true,
    credit: true,
    color: "#0d9488",
    summary: "Field and lab experience on funded marine and environmental research projects.",
    about:
      "Tidewell Research is a marine and environmental science group in Hobart running funded research on healthier oceans.",
    responsibilities:
      "You will assist with field sampling, lab processing and data entry on active research projects. You will get genuine research experience and a reference.",
    perks: [
      "Real field and lab experience",
      "Academic credit available",
      "Mentoring from research scientists",
      "Co-authorship opportunities",
    ],
    requirements: [
      "Studying marine science, biology or environmental science",
      "Comfortable with field work",
      "Careful with data and samples",
      "Available full-time over the placement",
    ],
    questions: baseQuestions(),
  },
  {
    id: "finance-analyst-intern",
    role: "Finance Analyst Intern",
    companyId: "ledgerline",
    company: "Ledgerline",
    location: "Melbourne, VIC",
    mode: "Hybrid",
    workType: "Part-time",
    field: "Finance",
    classification: "Banking & Financial Services (Analysis & Reporting)",
    salary: "$32 – $37 per hour",
    duration: "12 weeks",
    postedDaysAgo: 4,
    applicantVolume: "Typical",
    paid: true,
    friendly: false,
    credit: true,
    color: "#16a34a",
    summary: "Build financial models and reports supporting advisory work for growing businesses.",
    about:
      "Ledgerline's advisory team helps businesses plan and grow. Interns support analysis that informs real client decisions.",
    responsibilities:
      "You will help build financial models, prepare reports and support client advisory sessions. You will strengthen your analytical and commercial skills.",
    perks: [
      "Advisory exposure",
      "Academic credit available",
      "Mentoring toward finance careers",
      "Hybrid working in Melbourne",
    ],
    requirements: [
      "Studying finance, economics or commerce",
      "Strong Excel and modelling basics",
      "Analytical and detail-focused",
      "Available 2-3 days per week for 12 weeks",
    ],
    questions: baseQuestions(),
  },
  {
    id: "it-support-intern",
    role: "IT Support Intern",
    companyId: "northstar-systems",
    company: "Northstar Systems",
    location: "Brisbane, QLD",
    mode: "On-site",
    workType: "Casual",
    field: "Technology",
    classification: "Information & Communication Technology (Help Desk & IT Support)",
    salary: "$28 – $32 per hour",
    duration: "12 weeks",
    postedDaysAgo: 2,
    applicantVolume: "High",
    paid: true,
    friendly: true,
    credit: false,
    color: "#22c7a9",
    summary: "Front-line IT support experience — perfect first internship for help-desk careers.",
    about:
      "Northstar Systems supports enterprise platforms. Our help-desk team is a great first step for students starting in IT.",
    responsibilities:
      "You will help triage support tickets, set up devices, document fixes and support staff onboarding. You will build practical, in-demand IT support skills.",
    perks: [
      "First-internship friendly",
      "Hands-on help-desk experience",
      "Mentoring from IT support leads",
      "Pathway to graduate IT roles",
    ],
    requirements: [
      "Studying IT, computer science or similar",
      "Friendly, patient problem-solver",
      "Basic hardware and OS knowledge",
      "Available 2-3 days per week for 12 weeks",
    ],
    questions: baseQuestions(),
  },
  {
    id: "graphic-design-intern",
    role: "Graphic Design Intern",
    companyId: "sunday-studio",
    company: "Sunday Studio",
    location: "Melbourne, VIC",
    mode: "Hybrid",
    workType: "Casual",
    field: "Design",
    classification: "Design & Architecture (Graphic Design)",
    salary: "$29 – $33 per hour",
    duration: "10 weeks",
    postedDaysAgo: 6,
    applicantVolume: "Typical",
    paid: true,
    friendly: true,
    credit: true,
    color: "#ff6b4a",
    summary: "Create real brand and social assets with a supportive creative team.",
    about:
      "Sunday Studio is a brand and content studio. Our design team creates identity and social assets for lifestyle brands.",
    responsibilities:
      "You will design social assets, support brand projects and help prepare client presentations. You will grow a real, varied portfolio.",
    perks: [
      "Portfolio-building client work",
      "Academic credit available",
      "Mentoring from senior designers",
      "Hybrid working in Melbourne",
    ],
    requirements: [
      "Studying graphic design or visual communication",
      "Skilled in the Adobe suite or Figma",
      "A folio that shows your range",
      "Available 2 days per week for 10 weeks",
    ],
    questions: baseQuestions([
      {
        id: "portfolio",
        label: "Please share a link to your portfolio or folio.",
        type: "text",
        required: true,
      },
    ]),
  },
];

export const studentPlans = [
  {
    name: "Free",
    price: "$0",
    priceNum: 0,
    period: "forever",
    description: "Everything you need to start your internship search.",
    features: [
      "Browse all internships",
      "Apply with your profile",
      "Save up to 5 internships",
      "Basic application tracker",
    ],
    featured: false,
    badge: null as string | null,
    ctaLabel: "Get started free",
    ctaHref: "/register",
  },
  {
    name: "Plus",
    price: "$9.99",
    priceNum: 9.99,
    period: "per month",
    description: "Stand out to employers and track your progress.",
    features: [
      "Everything in Free",
      "Featured profile — 2× employer views",
      "Unlimited saved internships",
      "Application analytics & insights",
      "Monthly résumé review",
      "Early access to new listings",
      "Priority email support",
    ],
    featured: true,
    badge: "Most popular" as string | null,
    ctaLabel: "Start Plus",
    ctaHref: "/checkout/student?plan=Plus",
  },
  {
    name: "Pro",
    price: "$24.99",
    priceNum: 24.99,
    period: "per month",
    description: "Maximum visibility and personalised career coaching.",
    features: [
      "Everything in Plus",
      "Top placement in employer searches",
      "Unlimited résumé reviews",
      "Interview preparation toolkit",
      "Direct message employers",
      "Monthly career coaching session",
      "Dedicated career advisor",
    ],
    featured: false,
    badge: null as string | null,
    ctaLabel: "Start Pro",
    ctaHref: "/checkout/student?plan=Pro",
  },
];

export const plans = [
  {
    name: "Starter",
    price: "$49",
    priceNum: 49,
    period: "per listing",
    description: "A focused launch for one internship opportunity.",
    features: ["1 active listing", "Verified employer badge", "Applicant inbox"],
    featured: false,
  },
  {
    name: "Growth",
    price: "$150",
    priceNum: 150,
    period: "per month",
    description: "For growing teams building a repeatable intern pipeline.",
    features: ["5 active listings", "Featured placement", "Candidate insights"],
    featured: true,
  },
  {
    name: "Scale",
    price: "$390",
    priceNum: 390,
    period: "per month",
    description: "High-volume university and graduate recruitment.",
    features: ["Unlimited listings", "Priority campaigns", "Team analytics"],
    featured: false,
  },
];

export const employerFeatures = [
  {
    category: "Listings",
    rows: [
      { label: "Active internship listings", values: ["1", "5", "Unlimited"] as const },
      { label: "Listing duration", values: ["30 days", "60 days", "90 days"] as const },
      { label: "Featured placement", values: [false, true, "Premium"] as const },
    ],
  },
  {
    category: "Applicants",
    rows: [
      { label: "Applicant management", values: ["Basic inbox", "Advanced", "Enterprise"] as const },
      { label: "Candidate shortlisting", values: [false, true, true] as const },
      { label: "Candidate filters & insights", values: [false, true, "Advanced"] as const },
    ],
  },
  {
    category: "Branding & reach",
    rows: [
      { label: "Branded employer profile page", values: [false, true, true] as const },
      { label: "University partnerships", values: [false, false, true] as const },
      { label: "Team member logins", values: ["1", "3", "Unlimited"] as const },
    ],
  },
  {
    category: "Support & analytics",
    rows: [
      { label: "Customer support", values: ["Email", "Priority email", "Dedicated manager"] as const },
      { label: "Analytics dashboard", values: [false, true, "Advanced"] as const },
      { label: "Onboarding session", values: [false, false, true] as const },
    ],
  },
];

export const testimonials = [
  {
    quote:
      "The filters understood what I actually needed as a student. I found a paid, credit-eligible design internship in three days.",
    name: "Maya Chen",
    role: "UX student, QUT",
    initials: "MC",
  },
  {
    quote:
      "We stopped paying agency rates to reach the wrong audience. Interns Store put our role directly in front of motivated students.",
    name: "Jordan Wells",
    role: "People Lead, Canopy Labs",
    initials: "JW",
  },
  {
    quote:
      "The application tracker made my first search feel manageable. I always knew what to do next.",
    name: "Isaac Brown",
    role: "Business graduate, UQ",
    initials: "IB",
  },
] as const;

export const studentFaqs = [
  {
    q: "Is Interns Store completely free for students?",
    a: "Yes. Searching, saving roles, building a profile, applying and tracking applications are free for students and recent graduates.",
  },
  {
    q: "Can I apply if I have no previous experience?",
    a: "Absolutely. Look for the First Internship Friendly and No Experience Required badges. These roles are intentionally designed for first-time applicants.",
  },
  {
    q: "Can I find internships eligible for academic credit?",
    a: "Yes. Academic-credit eligibility is a dedicated filter and is clearly shown on every relevant listing.",
  },
  {
    q: "How does the application tracker work?",
    a: "Saved, applied, interviewing and offer stages appear in one simple timeline, so you can manage every opportunity without spreadsheets.",
  },
  {
    q: "Does Interns Store support international students?",
    a: "Yes. Employers can show work-right requirements clearly, and our guidance explains what to check before applying.",
  },
] as const;

export const posts = [
  {
    slug: "first-internship-cv",
    title: "How to write your first internship CV",
    excerpt:
      "No industry experience yet? Build a credible CV from projects, coursework, volunteering and transferable skills.",
    category: "CV Lab",
    date: "2026-06-08",
    read: "7 min read",
    color: "from-blue-700 to-blue-500",
  },
  {
    slug: "industries-hiring-interns-2026",
    title: "The Australian industries hiring interns in 2026",
    excerpt:
      "Technology, renewables, healthcare and professional services are opening more structured student pathways.",
    category: "Market Guide",
    date: "2026-05-29",
    read: "6 min read",
    color: "from-emerald-600 to-mint-500",
  },
  {
    slug: "paid-vs-unpaid-internships",
    title: "Paid vs unpaid internships in Australia",
    excerpt:
      "Understand the difference between a lawful vocational placement and productive work that should be paid.",
    category: "Know Your Rights",
    date: "2026-05-19",
    read: "8 min read",
    color: "from-orange-600 to-coral-500",
  },
  {
    slug: "host-a-great-internship",
    title: "How employers can host an internship students recommend",
    excerpt:
      "Clear outcomes, real mentorship and useful feedback turn a short placement into a lasting talent pipeline.",
    category: "For Employers",
    date: "2026-05-03",
    read: "5 min read",
    color: "from-violet-700 to-blue-500",
  },
] as const;

export const team = [
  { name: "Manula Ranasinghage", role: "Product & Experience", initials: "MR" },
  { name: "Vanshil Radadiya", role: "Marketplace Operations", initials: "VR" },
  { name: "Joao Albuquerque", role: "Employer Growth", initials: "JA" },
  { name: "Riad Hossain", role: "Trust & Marketing", initials: "RH" },
] as const;

export const studyFields = [
  "Technology",
  "Business",
  "Design",
  "Engineering",
  "Health",
  "Science",
  "Law",
  "Education",
  "Finance",
  "Marketing",
] as const;

export const locations = [
  "Remote",
  "Brisbane, QLD",
  "Sydney, NSW",
  "Melbourne, VIC",
  "Perth, WA",
  "Adelaide, SA",
  "Canberra, ACT",
  "Gold Coast, QLD",
  "Hobart, TAS",
] as const;

export function getCompany(id: string): Company | undefined {
  return companies.find((company) => company.id === id);
}

export function getInternship(id: string): Internship | undefined {
  return internships.find((item) => item.id === id);
}
